[book]
authors = ["Josh McKinney"]
language = "en"
multilingual = false
src = "src"
title = "Ratatui Documentation"

[output.html]
git-repository-url = "https://github.com/ratatui-org/ratatui-book"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/ratatui-org/ratatui-book/edit/main/{path}"
